AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: |
  CRUDAWSSamApp
  Sample SAM Template for CRUDAWSSamApp
Globals:
  Function:
    Timeout: 5
Resources:
  MoviesApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors: "'*'"
  MoviesTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String
  MoviesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: movies/
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MoviesTable
      Environment:
        Variables:
          MOVIES_TABLE: !Ref MoviesTable
      Events:
        MoviesGet:
          Type: Api
          Properties:
            Path: /movies
            Method: get
            RestApiId: !Ref MoviesApi
        MoviesPost:
          Type: Api
          Properties:
            Path: /movies
            Method: post
            RestApiId: !Ref MoviesApi
        MoviesDelete:
          Type: Api
          Properties:
            Path: /movies
            Method: delete
            RestApiId: !Ref MoviesApi
        MoviesUpdate:
          Type: Api
          Properties:
            Path: /movies
            Method: put
            RestApiId: !Ref MoviesApi
      Handler: app.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64
Outputs:
  MoviesApiUrl:
    Description: API Gateway endpoint for Movies
    Value: !Sub https://${MoviesApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/movies